apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CA_B64>
    server: https://10.127.247.182:6443
  name: kubekey
contexts:
- context:
    cluster: kubekey
    user: kubernetes-admin
  name: kubernetes-admin@kubekey
current-context: kubernetes-admin@kubekey
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: <CERT_B64>
    client-key-data: <KEY_B64>
